### ISSUE TITLE
Give map owners option to disable exports

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/OTM2#1359]

**Comment by dboyer** [comment]
Just make this an option on the basic information tab of the management page.

**Comment by jwalgran** [comment]
@dboyer Should we allow any map administrator to disable exports, or only the map owner?

**Comment by dboyer** [comment]
I think of exports as similar to something like setting up a custom field or using the bulk uploader. I think those features are open to map admins so I'm fine with map admin rather than just map owner.
