### ISSUE TITLE
Add "Last Updated" advanced search filter

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/OTM2#1420]
Filter should support a date range and look for trees/plots/green infrastructure last updated within that range. See screenshot of design. 
![advanced_search](https://cloud.githubusercontent.com/assets/516764/3247565/881f28ce-f185-11e3-8110-d4631b1704e3.png)

**Comment by jwalgran** [comment]
Add last updated field to map_feature. Follow Django best practices.
Updating a tree or photo updates the date on the corresponding map feature.
Add a script or migration to backfill the last updated date.
Update web UI
Update default advanced search to include last updated field
Script to update advanced search config in existing instances.

**Comment by dboyer** [comment]
The label on the search is "Updated on." If I entered March 13-16, would I see any trees edited between those dates or only trees whose last edit is March 13-16? If it's the latter, we need to change the text to Last Updated.

**Comment by maurizi** [comment]
It is the latter.  I'll get a PR up to change the label.

On Wed, Mar 18, 2015 at 8:02 PM, dboyer <notifications@github.com> wrote:

> The label on the search is "Updated on." If I entered March 13-16, would I
> see any trees edited between those dates or only trees whose last edit is
> March 13-16? If it's the latter, we need to change the text to Last Updated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenTreeMap/OTM2/issues/1420#issuecomment-83228702>.
>



-- 
Michael V. Maurizi Jr
Software Developer
Azavea |  340 N 12th St, Suite 402, Philadelphia, PA
mmaurizi@azavea.com  | T 215.558.6190
Web azavea.com <http://www.azavea.com/>  |  Blog azavea.com/blogs
<http://www.azavea.com/Blogs>  | Twitter @azavea <http://twitter.com/azavea>
