### ISSUE TITLE
Attempting to post an empty comment redirects to an unstyled page

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/OTM2#1596]
1. Log in
  1. Go to https://www.opentreemap.org/edmonton/features/130854/
  1. Leave the comment box empty and click "Post"

![screen shot 2014-09-10 at 2 26 20 pm](https://cloud.githubusercontent.com/assets/17363/4222976/ff29fa78-3917-11e4-88dd-fd7f275628e5.png)

**Comment by dboyer** [comment]
I no longer get an unstyled page but instead a new empty comment box and Post button is added to the detail page every time I try to post an empty comment.
