### ISSUE TITLE
The bulk importer page needs to educate users about how to format their CSVs

### ISSUE THREAD

**Issue by maurizi** [OpenTreeMap/OTM2#1795]
We have rather stringent requirements on CSV column header names, but they are not shown or mentioned anywhere in the page.  Perhaps we should add a section on the main "Bulk Uploader" page?

**Comment by RickMohr** [comment]
Details of completing this task:
* Complete instructional PDF (needs to cover custom fields)
* Complete 2 CSV templates (one for species, one for trees), which I believe (per @dboyer) will not include custom fields
* Get design input if desired on location/wording of links to PDF and templates on "Bulk Uploader" page
* Add links to "Bulk Uploader" page

**Comment by ctaylo37** [comment]
Here's my recommendation for design:

![2015_01_07_uploader_instructions](https://cloud.githubusercontent.com/assets/5880793/5648019/064203de-9659-11e4-9b09-767ff7b50ade.png)

**Comment by RickMohr** [comment]
Looks good. I say check it in and we can tweak it further if desired.
