### ISSUE TITLE
Importer: don't make me waste an hour

### ISSUE THREAD

**Issue by RickMohr** [OpenTreeMap/OTM2#1849]
Loading and validating 250,000 trees takes an hour, and you might have a systemic error you need to correct in your csv (like oops, all my dates are formatted like 12/10/2014 but OTM requires 2014-12-10).

Two solutions come to mind:

1) Preflight - allow importing the first 100 or 1000 trees. ("Add to Tree Map" would be disabled for such imports.)

2) Allow viewing imported rows while the import is still in progress.  ("Add to Tree Map" would be disabled until the import was complete.) With this option we'd want a "Cancel" action for in-progress imports.

**Comment by maurizi** [comment]
Fixed by #1877
