### ISSUE TITLE
Importer: tree created if "Tree Present" is false but a tree column has a value

### ISSUE THREAD

**Issue by RickMohr** [OpenTreeMap/OTM2#1859]
If the "Tree Present" column is false for a tree import row, presumably the intent is to create a planting site but not a tree. However if a tree column (e.g. "Diameter" or a custom tree field like "Tree: Owner") contains a value we create a tree anyway. I don't think we should.

**Comment by RickMohr** [comment]
What should we do if there's a "Tree Present" column but the value is blank for a row?
1) Assume "True" and create a tree
2) Assume "False" and don't create a tree (even if tree fields are present)
3) If tree fields are present, create a tree; otherwise, don't create a tree

Same question if there is no "Tree Present" column.

**Comment by RickMohr** [comment]
My votes: 
If there is no "Tree Present" column, #3.
If the value is blank for a row, #3.

**Comment by jwalgran** [comment]
I agree. "Tree Present" is just an override, so if we don't have the column, or the column does not have a truth-ish value, then we should fall back to only creating a tree if we have other tree-related fields in the row.

**Comment by dboyer** [comment]
I agree with both of you.

**Comment by RickMohr** [comment]
Fixed by #1915
