### ISSUE TITLE
Stop storing importer error text in the database

### ISSUE THREAD

**Issue by steventlamb** [OpenTreeMap/OTM2#1880]
Storing importer error text in the database makes lazy translation impossible. Lazy translation objects must be forced to a string before being serialized, so at best, we would have to force them to strings at the moment the error was saved, not the moment it is read by a user. This would especially be a problem for english speakers providing support for international clients.

It is an anti-pattern to store human readable text in the database when a corresponding error code exists, and some lesser but frustrating manifestations of this problem can also turn up. For example, if we later change error text to be more helpful, we'll have to migrate the records that exist in the database, or code around them. For this reason, the following solution should be done as soon as possible:

The error handling of the importer should be modified to store only error codes in the database. Then, when the error text is to be presented to the user, it can be looked up in the errors module and retrieved as a lazy translation object, forced to a translated string, and sent to the client.

**Comment by RickMohr** [comment]
It would be great to change this before we release, as it will be a more costly change once we have customer ports with error strings in the database. Much cheaper to fix now.

**Comment by dboyer** [comment]
If it's cheaper to fix now, let's do that. Thanks for raising the issue @steventlamb

**Comment by RickMohr** [comment]
Fixed by #1886
