### ISSUE TITLE
Using the OTM Mobile App

### ISSUE THREAD

**Issue by ytzvan** [OpenTreeMap/OTM2#1889]
Hello, I just installed a production version of Open Tree Map (no vagrant) and is running correctly. I want to add some trees via OpenTreeMap for iOS but I don't know where to start. I downloaded the mobile version of OpenTreeMap from the App Store, but only shows me the maps hosted in the OpenTreeMap Cloud. How can I use the mobile app with my hosted version? Do I need to compile an iOS version addressing my host?
Thanks.

**Comment by andrewbt** [comment]
Hi @ytzvan ! That's exciting you were able to stand up a production version of OpenTreeMap.

Unfortunately, the OpenTreeMap iOS app that's in the Apple App Store will only work with maps hosted in the OpenTreeMap cloud. If you want to use an app with your hosted version, you will need to build your own.

We have the code [here](https://github.com/OpenTreeMap/OpenTreeMap-iOS/), and while there are many branches the most up-to-date that should work with OTM2 is the "master" branch. However, the https://github.com/azavea/OpenTreeMap-iOS-skin repo is no longer relevant for the OTM2 app - it's intended for the (OTM1)[http://github.com/OpenTreeMap/OpenTreeMap]. The new app changed quite a bit and we haven't yet had the time to release an unbranded open source skin for it. You can try making your own app, but it will probably be fairly hard until we're able to find the time for this. Sorry we can't be of more help.

**Comment by andrewbt** [comment]
Also, if you have more questions, I'd recommend asking on our OpenTreeMap-User mailing list: https://groups.google.com/forum/?fromgroups#!forum/opentreemap-user You may be more likely to get a response!

**Comment by ytzvan** [comment]
Thanks @andrewbt I'll check the code and figure out how to make it work with my own OTM server, thanks!
