### ISSUE TITLE
Importer: Hide read only field from list of fields displayed as part of an import 

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/OTM2#1890]
I marked a row as TRUE in the read only column while testing the importer. I could still edit that tree once it was uploaded. Two possible things:

1. Can I edit it because I'm the map owner? I'm fine with enabling administrators to always edit trees, but I need to put that in the documentation.

2. Is the Read Only column not actually causing trees to be made read only? If so, we should either fix it or get it out of the importer template.

**Comment by maurizi** [comment]
We have not yet implemented read only: https://github.com/OpenTreeMap/OTM2/issues/379

The field exists, but setting doesn't do anything

**Comment by dboyer** [comment]
Okay. I'm going to remove it from the template for now to avoid confusion and we can hopefully implement this soon.

**Comment by dboyer** [comment]
Let's hide this on the import status page too so as to not confuse users.

**Comment by RickMohr** [comment]
For now I'm going to remove "read only" from the list of fields the importer knows about. It won't show up as a legal field in the error message, and users will get an error if they include it in their csv.

**Comment by jwalgran** [comment]
@RickMohr I have been working on this, and am implementing the strategy you suggest.

**Comment by dboyer** [comment]
@jwalgran Will read only also be hidden from the fields shown on the import status page where it lists the trees in your import?

**Comment by jwalgran** [comment]
@dboyer  It looks like the tabs are only showing the columns that were in the original file. Since we no longer allow a "read only" field in the file, it won't show up as a column.

![screen shot 2015-01-13 at 12 39 10 pm](https://cloud.githubusercontent.com/assets/17363/5727667/14556542-9b22-11e4-9f35-48ce3afe448b.png)

**Comment by jwalgran** [comment]
![screen shot 2015-01-13 at 12 46 59 pm](https://cloud.githubusercontent.com/assets/17363/5727710/4c1d8eaa-9b22-11e4-92f9-b249573c3208.png)

**Comment by dboyer** [comment]
perfect
