### ISSUE TITLE
Importer: Import event counts are not unique to each map

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/OTM2#1891]
I got up to Tree Import number 15 on one test map. When I switched to a different test map, it listed my first import as tree import number 16 even though I hadn't done any imports for that map. It seems like the import event counts aren't unique to each map. I think they need to be or it's confusing for the user.

**Comment by RickMohr** [comment]
If we expend coding effort in this area I think we should do #1851 and remove the "import number" (really a DB ID which is why you see this behavior).

**Comment by dboyer** [comment]
@RickMohr I'm fine with that. This bug (#1891) is something I think we need to tackle in the 2 point black box card we have left. Not sure if we can fit #1851 in that as well.

**Comment by RickMohr** [comment]
@dboyer, what if we show the import date/time **instead of** the import ID? That would be simpler than converting the import ID to a treemap-specific "import number".

**Comment by dboyer** [comment]
@RickMohr Fine by me.
