### ISSUE TITLE
Importer: Change help text on species field error

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/OTM2#1892]
Change the text to say:

Species Field Error
Could not find this scientific name on the master species list. 
Select the suggested option below or click in the text box to select from the species list.

**Comment by RickMohr** [comment]
@dboyer, how about:
Click "Save" to accept the suggested option or click in the text box to select from the species list.

Also if it's a real species but not yet in their treemap the right solution would be to first import the species and then reimport the trees. Should we mention anything about that?

**Comment by dboyer** [comment]
@RickMohr How about:

Click "Save" to accept the suggested species or click in the text box to select from the species list. Use the species import tool to add new species to your map.

Too long?

**Comment by RickMohr** [comment]
![image](https://cloud.githubusercontent.com/assets/2162993/5727713/14c3befa-9b33-11e4-9d52-af3844398c32.png)

**Comment by dboyer** [comment]
Add a period after map, and I'm good with this. Thanks.

**Comment by RickMohr** [comment]
Here's another idea. Maybe we want some quick input from @ctaylo37? A "tips" link?

![image](https://cloud.githubusercontent.com/assets/2162993/5727819/df7154d2-9b33-11e4-9d62-98af0d748abd.png)
