### ISSUE TITLE
Importer: Trees can be edited from successfully added tab

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/OTM2#1896]
If trees were on the warnings tab, they are still added to the tree map when the user clicks "Add to Tree Map." At that point, they move to the successfully added tab but the Point X and Point Y columns are highlighted yellow and can still be edited. If edited, the tree moves back to the Ready to Add tab.

I think it's confusing for Point X and Point Y to be editable for only some trees on this tab. No other fields can be edited. It seems like trees moved to successfully added should no longer be editable. Thoughts?

**Comment by RickMohr** [comment]
Agreed, those fields should not be editable. Should they be highlighted? I think not.

**Comment by dboyer** [comment]
I don't think they need to be highlighted. Seems like it would be frustrating for something to be highlighted when you couldn't actually do anything to it.

**Comment by RickMohr** [comment]
This suggests we allow you to import the same tree twice (i.e. on top of another tree). That seems bad, since the tree that's "underneath" would be impossible to select or edit but would contribute to ecobenefits.

**Comment by dboyer** [comment]
I'm not sure I understand. How would the trees be imported twice?

**Comment by maurizi** [comment]
@RickMohr I suspected that might be the case, but I verfied with @dboyer that we don't add a *new* tree on top of an existing one, by checking that the Planting Site count remained the same.

I agree that nothing on the "Sucessfully Added" tab should be editable.

**Comment by RickMohr** [comment]
I raised a separate issue for this, #1903
