### ISSUE TITLE
Privacy error at opentreemap.org

### ISSUE THREAD

**Issue by RickMohr** [OpenTreeMap/OTM2#1900]
Browsing to http://www.opentreemap.org gives:

![image](https://cloud.githubusercontent.com/assets/2162993/5728431/28cdaf50-9b38-11e4-81a0-8f2aaa96cf50.png)

**Comment by jwalgran** [comment]
Safari, Chrome, and Firefox on my laptop all redirect successfully to https://. This may be platform specific.

**Comment by dboyer** [comment]
I'm not getting this error in IE either.

**Comment by RickMohr** [comment]
For me it works from my Azavea machine but not from my home machine, both Chrome/Windows.

**Comment by dboyer** [comment]
I tested outside the vpn and still couldn't get the issue.

**Comment by RickMohr** [comment]
Once I turned off the VPN I no longer had the issue. Closing.
