### ISSUE TITLE
Importer: prevent importing duplicate trees

### ISSUE THREAD

**Issue by RickMohr** [OpenTreeMap/OTM2#1903]
If you click "Add to Tree Map" for an import and later click "Add to Tree Map" again for that same import, we don't add a new tree on top of an existing one.

However, if you make two separate imports of the same file, the second import will show "nearby tree" warnings and if you click "Add to Tree Map" then we will add new trees on top of the existing ones.

We should have an **error** "there is already a tree at that location" in addition to our **warning** "there are nearby trees".

**Comment by dboyer** [comment]
@RickMohr So the warning would be if the tree were within 10 feet, but the tree would go on the error tab if it were the exact same location? What if the user had entered an OTM Plot ID number? It seems like it wouldn't be an error then since they were likely trying to update an existing tree.

**Comment by RickMohr** [comment]
Agreed.
