### ISSUE TITLE
Importer: Change error message on i-Tree region

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/OTM2#1905]
We need to provide more info on the i-Tree region error. Screenshot of current message is attached. I don't think provides enough info as to what the user needs to do. My suggested change:

There was an error with this field. This tree map intersects with more than one i-Tree region. Please specify the region associated with this i-Tree code (e.g. NoEastXXX:BDL OTHER). Region codes are available at ....

Do we have the region codes listed anywhere other than eco.py? I'm not sure how someone would know to enter SoCalCSMA or NoEastXXX.

![itree_error](https://cloud.githubusercontent.com/assets/516764/5740465/a53d473c-9bd1-11e4-824d-d1ca975574a0.png)

**Comment by RickMohr** [comment]
Perhaps better is to not flag an error and use `BDL OTHER` for all regions in this case.

**Comment by dboyer** [comment]
I think using the BDL OTHER code for the region covered by the map is fine since most regions have a BDL OTHER entry. That won't always be the case though, so I think we need to provide some information on how the user could specify the region code.

**Comment by dboyer** [comment]
It would be too difficult to explain how to fix these errors in a small pop-up box. My suggestion is to append the following sentence to each i-Tree related error.

Please consult the OpenTreeMap Species Import Guide for information on resolving this error.
