### ISSUE TITLE
Importer: New species doesn't calculate ecosystem benefits

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/OTM2#1906]
I used the species importer to add a new species and I included an i-Tree code, which the importer accepted. When I go to add a tree of that species (Celtis sinensis/Chinese Hackberry on a map in the Northeast region), it says that ecobenefits for the tree can't be calculated.

**Comment by RickMohr** [comment]
What i-Tree code did you use? We can only calculate detail in it's one of the ones in e.g. https://github.com/OpenTreeMap/ecobenefits/blob/master/data/output__NoEastXXX__aq_pm10_dep.csv

**Comment by dboyer** [comment]
I used NoEastXXX:BDL OTHER. The test map is phillyuploader on the dev server if you want to see.

**Comment by RickMohr** [comment]
I suspect that's because the tree is in PiedmtCLT, since only a few parts of Philadelphia to the north and west are in NoEastXXX. Can you try again with PiedmtCLT?

**Comment by dboyer** [comment]
I think you're right. Closing this.
