### ISSUE TITLE
Importer: Need styling on merge buttons

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/OTM2#1912]
See screenshot. The merge buttons in the species importer are difficult to see. 

![merge_buttons](https://cloud.githubusercontent.com/assets/516764/5744608/3e46b59e-9bf0-11e4-8d89-2b14f26fb3aa.png)

**Comment by RickMohr** [comment]
@dboyer, will this do?
![image](https://cloud.githubusercontent.com/assets/2162993/5761448/87e8cb6a-9ca9-11e4-8893-c114b61ee78b.png)

**Comment by dboyer** [comment]
@RickMohr Looks good.
