### ISSUE TITLE
Importer: Merging data on species records is not respecting merge

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/OTM2#1919]
I uploaded a file that included a species already in the system. it was marked as "Merge required" as the max diameter in the file was 50 and the max diameter already in OTM was 200. When I clicked that field, I received options to select 50 or 200. I selected 200 and then clicked "Merge with Match." The species was moved to the Ready to Add tab, but it still had 50 in the max diameter field. 

Will it be added with a max diameter of 50 or 200?

**Comment by dboyer** [comment]
Actually, are we respecting the max diameter field when adding trees? I was just able to add a tree with a diameter over 200 inches.

**Comment by dboyer** [comment]
This looks good in terms of the importer UI. Do we respect the limit when people are adding trees though?

**Comment by RickMohr** [comment]
We appear to enforce the species diameter limit when importing trees but not when adding them.

**Comment by dboyer** [comment]
Okay, closing this and opening #1928 as that's a separate bug.
