### ISSUE TITLE
Edit event: styling needed

### ISSUE THREAD

**Issue by RickMohr** [OpenTreeMap/OTM2#1921]
* Error message should be in red, and probably doesn't want a bullet
* Input box for start time is too wide

![image](https://cloud.githubusercontent.com/assets/2162993/5820268/c6074836-a091-11e4-8a8e-d21ab461c7f7.png)

**Comment by dboyer** [comment]
@RickMohr Should this be in the other repo?

**Comment by RickMohr** [comment]
Yup.
