### ISSUE TITLE
Eco Benefits 

### ISSUE THREAD

**Issue by jschmidt12** [OpenTreeMap/OTM2#1950]
Detroit's tree map (https://www.opentreemap.org/thegreeningofdetroitstreemap/map/?z=11/42.3958/-83.1576) has been using the importer and it has been working find but today they noticed that as they have added trees the Eco Benefits count isn't increasing the same amount as the trees added. Currently there are 1,046 total trees but only 995 are being counted in the benefits calculation. If you do a quick search you for trees missing Species or Diameter the count is ZERO. They claim every tree they have imported as the diameter and species.

**Comment by jwalgran** [comment]
Moved to another issue list
