### ISSUE TITLE
Species export never finishes

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/OTM2#1965]
I clicked the "export all species" button on the bottom of the bulk uploader page and it just indefinitely sits on the "preparing your export" pop-up. This is on production.

**Comment by jwalgran** [comment]
I did do this successfully last night.

**Comment by dboyer** [comment]
I ran into the issue on both phillytreemap and a new test map I just created.

**Comment by jwalgran** [comment]
I restarted the ``celeryd`` on both app servers and was able to export the species list from phillytreemap.

**Comment by dboyer** [comment]
This is true both on production and on the new release build.

**Comment by dboyer** [comment]
The export on the release build did finish after several minutes.

**Comment by jwalgran** [comment]
I exported the species from two different maps on our release build in 11 seconds and 13 seconds. My guess is that the celery workers were tied up, resulting in a long delay before the job started.
