### ISSUE TITLE
Import file with 260k+ rows stuck on Verifying 

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/OTM2#1979]
On the dev server

![screen shot 2015-03-18 at 12 22 03 pm](https://cloud.githubusercontent.com/assets/17363/6717420/7f99f722-cd69-11e4-8f74-d60dc7ba94b1.png)

~~I tried the import twice, and this same error appeared twice in the celery log~~

This was almost definitely caused by the fact that I restarted celeryd

```
[2015-03-18 14:19:54,011: ERROR/MainProcess] Task importer.tasks.run_import_event_validation[b6dfe41d-b38e-4881-b1ae-699a5b34fbcc] raised unexpected: WorkerLostError('Worker exited prematurely: signal 15 (SIGTERM).',)
Traceback (most recent call last):
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/billiard/pool.py", line 1169, in mark_as_worker_lost
    human_status(exitcode)),
WorkerLostError: Worker exited prematurely: signal 15 (SIGTERM).
```

**Comment by jwalgran** [comment]
Celery inspect shows the parent task for the entire import, but not the expected child tasks that process chunks of rows.

```
(env)otm@mail:/usr/local/otm/app/opentreemap$ ./manage.py celery inspect active
-> celery@mail.opentreemap.org: OK
    * {u'args': u"(u'tree', 28, <_io.BytesIO object at 0x466ead0>)", u'time_start': 4313676.700145768, u'name': u'importer.tasks.run_import_event_validation', u'delivery_info': {u'priority': 0, u'redelivered': None, u'routing_key': u'celery', u'exchange': u'celery'}, u'hostname': u'celery@mail.opentreemap.org', u'acknowledged': True, u'kwargs': u'{}', u'id': u'037f5b3a-4cb2-4543-9918-94d08c9af5b1', u'worker_pid': 5295}

**Comment by jwalgran** [comment]
Reproduced on dev and release, so this is not a recent regression.

**Comment by jwalgran** [comment]
Reproduced on production

**Comment by jwalgran** [comment]
I just uploaded a large file to dev and the verify is running.

![screen shot 2015-04-08 at 8 44 03 am](https://cloud.githubusercontent.com/assets/17363/7049067/9974cb96-ddcb-11e4-897e-abe509c86b35.png)

The job does not hang in all cases.

**Comment by jwalgran** [comment]
I ran an import job with 100,002 full rows of data (not just coordinates) on my dev VM

As the ``_validate_rows`` jobs scrolled by in celery log, a worker was killed:

```
[2015-04-08 13:22:09,190: ERROR/MainProcess] Task importer.tasks._validate_rows[48070c36-52ba-4f1a-9bc5-3c00fd202a70] raised unexpected: WorkerLostError('Worker exited prematurely: signal 9 (SIGKILL).',)
Traceback (most recent call last):
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/billiard/pool.py", line 1169, in mark_as_worker_lost
    human_status(exitcode)),
WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL).
```

After a period of successful processing, the job now shows on the Bulk Import tab stuck a 85,432 / 100,002. The celery “active” list is empty.

```
./manage.py celery inspect active
-> celery@precise64: OK
    - empty -
```

Row statuses

```
otm=# select status, count(*) from importer_treeimportrow where import_event_id = 262 group by status;
 status | count
--------+-------
      1 | 21425
      2 |     1
      4 | 64006
      3 | 14570
```

The sum of statuses 1, 2, and 4 matches the count 85,432.

``GenericImportRow`` lists the statuses as 

```
SUCCESS = 0
ERROR = 1
WARNING = 2
WAITING = 3
VERIFIED = 4
```

The question is, why are these rows ``WAITING`` without a celery task to process them.

**Comment by RickMohr** [comment]
@jwalgran, Django in debug mode accumulates memory and the task is killed by the oomkiller.

**Comment by jwalgran** [comment]
While trying to debug the problem I raised an exception in ``run_import_event_validation`` and found that the event appears hung because, because the task dies quietly and the import status is never changed away from “Verifying”. If anything stops the ``run_import_event_validation`` task (i.e.  the oomkiller)   before it has a chance to launch the subtasks, we will end up in this state.
