### ISSUE TITLE
Social media sharing buttons on tree detail page

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/OTM2#413]
Facebook, Twitter, and Google Plus - buttons on the tree detail page in order to share the whole page.

**Comment by RickMohr** [comment]
Is the idea that hovering over the "Share" link reveals the Facebook and Twitter buttons? If so, do we care that it wouldn't work on mobile? If not, how should it work exactly?

**Comment by dboyer** [comment]
@RickMohr I believe you click the share button to see the Facebook, Twitter, and Google Plus buttons. This was a design from @mtedeschi but since he's out of the country, let's defer to @jfrankl .

**Comment by jfrankl** [comment]
Let's activate that button with a click rather than hover. Let me know if you have other questions about it or want to talk through it.

**Comment by jwalgran** [comment]
Shown in sprint review today
